name: pr
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
on:
  pull_request:
    branches:
      - v1.x
      - v2.x
      - v3.x
jobs:
  build:
    name: Publish latest
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout the Git repository
        uses: actions/checkout@v3
      - name: Build images
        run: |
          ./scripts/build .