name: pr

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

on:
  pull_request:
    branches:
      - v1.x
      - v2.x
      - v3.x

jobs:
  build:
    name: Publish latest
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout the Git repository
        uses: actions/checkout@v3
      # testing will delete
      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      # end testing will delete
      - name: Build images
        run: |
          ./scripts/build .